In [1]:
import pandas as pd

In [2]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 200)

In [3]:
df = pd.read_parquet("/home/yasida_wanigatunga/projects/nyc-taxi-batch-etl/data/raw/yellow_tripdata_2023-01.parquet")

In [4]:
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.30,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.90,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.90,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.10,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.40,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3066761,2,2023-01-31 23:58:34,2023-02-01 00:12:33,NaN,3.05,NaN,None,107,48,0,15.80,0.00,0.5,3.96,0.0,1.0,23.76,NaN,NaN
3066762,2,2023-01-31 23:31:09,2023-01-31 23:50:36,NaN,5.80,NaN,None,112,75,0,22.43,0.00,0.5,2.64,0.0,1.0,29.07,NaN,NaN
3066763,2,2023-01-31 23:01:05,2023-01-31 23:25:36,NaN,4.67,NaN,None,114,239,0,17.61,0.00,0.5,5.32,0.0,1.0,26.93,NaN,NaN
3066764,2,2023-01-31 23:40:00,2023-01-31 23:53:00,NaN,3.15,NaN,None,230,79,0,18.15,0.00,0.5,4.43,0.0,1.0,26.58,NaN,NaN
3066765,2,2023-01-31 23:07:32,2023-01-31 23:21:56,NaN,2.85,NaN,None,262,143,0,15.97,0.00,0.5,2.00,0.0,1.0,21.97,NaN,NaN

In [5]:
df.shape

(3066766, 19)

In [6]:
df.dtypes

VendorID                          int64
tpep_pickup_datetime     datetime64[us]
tpep_dropoff_datetime    datetime64[us]
passenger_count                 float64
trip_distance                   float64
RatecodeID                      float64
store_and_fwd_flag               object
PULocationID                      int64
DOLocationID                      int64
payment_type                      int64
fare_amount                     float64
extra                           float64
mta_tax                         float64
tip_amount                      float64
tolls_amount                    float64
improvement_surcharge           float64
total_amount                    float64
congestion_surcharge            float64
airport_fee                     float64
dtype: object

In [7]:
df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.3,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.9,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.9,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.1,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.4,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00

In [8]:
df.isna().sum()

VendorID                     0
tpep_pickup_datetime         0
tpep_dropoff_datetime        0
passenger_count          71743
trip_distance                0
RatecodeID               71743
store_and_fwd_flag       71743
PULocationID                 0
DOLocationID                 0
payment_type                 0
fare_amount                  0
extra                        0
mta_tax                      0
tip_amount                   0
tolls_amount                 0
improvement_surcharge        0
total_amount                 0
congestion_surcharge     71743
airport_fee              71743
dtype: int64

In [9]:
df[["passenger_count", "trip_distance", "fare_amount", "total_amount"]].describe()

       passenger_count  trip_distance   fare_amount  total_amount
count     2.995023e+06   3.066766e+06  3.066766e+06  3.066766e+06
mean      1.362532e+00   3.847342e+00  1.836707e+01  2.702038e+01
std       8.961200e-01   2.495838e+02  1.780782e+01  2.216359e+01
min       0.000000e+00   0.000000e+00 -9.000000e+02 -7.510000e+02
25%       1.000000e+00   1.060000e+00  8.600000e+00  1.540000e+01
50%       1.000000e+00   1.800000e+00  1.280000e+01  2.016000e+01
75%       1.000000e+00   3.330000e+00  2.050000e+01  2.870000e+01
max       9.000000e+00   2.589281e+05  1.160100e+03  1.169400e+03

In [10]:
for col in ["VendorID", "RatecodeID", "payment_type"]:
    print(df[col].value_counts(dropna=False).head(10))

VendorID
2    2239399
1     827367
Name: count, dtype: int64
RatecodeID
1.0     2839305
2.0      114239
NaN       71743
5.0       15043
99.0      13106
3.0        8958
4.0        4366
6.0           6
Name: count, dtype: int64
payment_type
1    2411462
2     532241
0      71743
4      33297
3      18023
Name: count, dtype: int64

In [11]:
df["tpep_pickup_datetime"].min(),  
df["tpep_pickup_datetime"].max()

Timestamp('2023-02-01 00:56:53')

In [12]:
df.duplicated().sum()

0

In [13]:
key = ["VendorID", "tpep_pickup_datetime", "tpep_dropoff_datetime",
       "PULocationID", "DOLocationID", "fare_amount"]
print("business-key duplicates:", df.duplicated(subset=key).sum())

business-key duplicates: 165

In [14]:
rows_extracted = len(df)
rows_extracted

3066766

In [17]:
len(df)

3066766

In [15]:
df = df.drop_duplicates()
df.duplicated().sum()

0

In [16]:
rows_duplicate = rows_extracted - len(df)
rows_duplicate

0

In [22]:
import pandas as pd
df = pd.read_parquet("/home/yasida_wanigatunga/projects/nyc-taxi-batch-etl/data/raw/yellow_tripdata_2023-01.parquet")
df["dur"] = (df.tpep_dropoff_datetime - df.tpep_pickup_datetime).dt.total_seconds()/60

ms = pd.Timestamp("2023-01-01"); me = pd.Timestamp("2023-02-01")

print("out of month     :", (~df.tpep_pickup_datetime.between(ms, me, inclusive="left")).sum())
print("zero distance    :", (df.trip_distance <= 0).sum())
print("distance > 200mi :", (df.trip_distance > 200).sum())
print("negative fare    :", (df.fare_amount < 0).sum())
print("total <= 0       :", (df.total_amount <= 0).sum())
print("duration < 0.5min:", (df.dur < 0.5).sum())
print("duration > 24h   :", (df.dur > 1440).sum())

out of month     : 48
zero distance    : 45862
distance > 200mi : 70
negative fare    : 25049
total <= 0       : 25772
duration < 0.5min: 26159
duration > 24h   : 25